### ISSUE TITLE
Honor System

### ISSUE THREAD

**Issue by kaytotes** [kaytotes/Nozdormu#6]
Honor system wasn't implemented until 1.4.0.

Should this be disabled? When it is enabled should it be the original vanilla classic honor system?

**Comment by uutfboomheadshot** [comment]
Use WotLK vendors for PvP gear but release progressively.
Titles based on amount of pvp kills.

Private **50** Scout
Corporal **250** Grunt
Sergeant **500** Sergeant
Master Sergeant **1000** Senior Sergeant
Sergeant Major **2000** First Sergeant
Knight **2500** Stone Guard
Knight-Lieutenant **3000** Blood Guard
Knight-Captain **4000** Legionnaire
Knight-Champion **5000** Centurion
Lieutenant Commander **7500** Champion
Commander **12500** Lieutenant General
Marshal **20000** General
Field Marshal **22500 **Warlord
Grand Marshal **25000** High Warlord
Of the Alliance **50000** Of the Horde

**Comment by uutfboomheadshot** [comment]
Honor system has been implemented as described in the Wiki.

**Comment by kaytotes** [comment]
Some issues found, reopening.

**Comment by kaytotes** [comment]
Ported to SunwellCore and fixed issues.
